# Generated by Django 4.1 on 2023-05-07 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orderid',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
