# Generated by Django 4.1.5 on 2023-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/products/'),
        ),
    ]
