# Generated by Django 4.1.5 on 2023-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='photo_url',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
