# Generated by Django 4.1.5 on 2023-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_good_photo_url_alter_good_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price_10k',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_20k',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_5k',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_many',
            field=models.FloatField(null=True),
        ),
    ]
