# Generated by Django 4.1.5 on 2023-01-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_good_price_10k_alter_good_price_20k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price_10k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_20k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_5k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_many',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
